/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/Cloud.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cloud(props) {
  const { nodes, materials } = useGLTF('models/Cloud.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere001.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Sphere003.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Sphere004.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Sphere005.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Sphere006.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Sphere007.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Sphere008.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Sphere010.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Sphere011.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Sphere012.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Sphere013.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Sphere014.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Sphere016.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Sphere017.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Sphere018.geometry} material={materials._crayfishdiffuse} />
    </group>
  )
}

useGLTF.preload('models/Cloud.glb')

