/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/cloud4.glb 
Author: farhad.Guli (https://sketchfab.com/farhad.Guli)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/clouds-116f49c23c4347eba340d0f59b0601f7
Title: Clouds
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cloud4(props) {
  const { nodes, materials } = useGLTF('models/cloud4.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_3.geometry} material={materials.DEFAULT} position={[-228.141, -280.375, -22.734]} />
      </group>
    </group>
  )
}

useGLTF.preload('models/cloud4.glb')
