/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/Cloud5.glb 
Author: RunemarkStudio (https://sketchfab.com/runemarkstudio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cartoon-cloud-f31be54812a348df86d94171098dae19
Title: Cartoon Cloud
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cloud5(props) {
  const { nodes, materials } = useGLTF('models/Cloud5.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} >

        <meshStandardMaterial onBeforeCompile={(shader) => {
          shader.fragmentShader = shader.fragmentShader.replace(`vec4 diffuseColor = vec4( diffuse, opacity );`,
            `float fadeDist = 25.0;
  float dist = length(vViewPosition);
  float fadeOpacity = smoothstep(fadeDist, 0.0, dist);
  vec4 diffuseColor = vec4(diffuse, fadeOpacity * opacity);`)

          console.log(shader.fragmentShader)

        }} envMapIntensity={2} transparent opacity={1} />
      </mesh>

    </group>
  )
}

useGLTF.preload('models/Cloud5.glb')
