/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/plane.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Plane(props) {
  const { nodes, materials } = useGLTF('models/plane.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group1111588455.geometry} material={materials.mat21} />
    </group>
  )
}

useGLTF.preload('models/plane.glb')
