/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/scene.gltf 
Author: TheDirector (https://sketchfab.com/The-Director)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cameraman-62ea2ffb7d37476e8e5f3e93c2ef5aea
Title: ---CameraMan---
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Scene(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('models/scene.gltf')
  const { actions, names } = useAnimations(animations, group)

  console.log(names)
  useEffect(() => {
    actions[names[0]].play()
  }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="40e54ed395d3484693493cec5191b3befbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature">
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_87" />
                    <group name="Object_89" />
                    <group name="Object_91" />
                    <group name="Object_93" />
                    <skinnedMesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.ClothesAndSkin} skeleton={nodes.Object_88.skeleton} />
                    <skinnedMesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.ClothesAndSkin} skeleton={nodes.Object_90.skeleton} />
                    <skinnedMesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.ClothesAndSkin} skeleton={nodes.Object_92.skeleton} />
                    <skinnedMesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.ClothesAndSkin} skeleton={nodes.Object_94.skeleton} />
                  </group>
                </group>
                <group name="Bottoms" />
                <group name="Body" />
                <group name="Tops" />
                <group name="Shoes" />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/scene.gltf')
